Add post_push hook for local builds
Change mode for all files from windows new line to linux new line

diff --git a/php/php56-fpm/hooks/post_push b/php/php56-fpm/hooks/post_push
--- a/php/php56-fpm/hooks/post_push
+++ b/php/php56-fpm/hooks/post_push
@@ -4,17 +4,23 @@
 
 echo "[***] Post_push hook starting..."
 
-## Build on Dockerhub
-ROOT_DIR="/src/$BUILD_CODE"
-ENV_FILE="$ROOT_DIR/.env"
+if [ -z "$BUILD_CODE" ]; then
+	## Build local
+	echo "[---] Push the image taged as latest."
+	docker push $IMAGE_NAME
+else
+	## Build on Dockerhub
+	ROOT_DIR="/src/$BUILD_CODE"
+	ENV_FILE="$ROOT_DIR/.env"
 
-if [ ! -e "$ENV_FILE" ]; then
-	echo "$ENV_FILE not found!"
-	exit 1
+	if [ ! -e "$ENV_FILE" ]; then
+		echo "$ENV_FILE not found!"
+		exit 1
+	fi
+
+	echo "[---] Load: $ENV_FILE"
+	source $ENV_FILE
 fi
-
-echo "[---] Load: $ENV_FILE"
-source $ENV_FILE
 
 if [ -z "$PHP56_VERSION" ]; then
 	echo "PHP56_VERSION is empty!"
