Update Images
### Updates
Apache from:
- 2.4.67 to 2.4.68

PHP from:
- 8.5.6 to 8.5.10
- 8.4.21 to 8.4.25
- 8.3.31 to 8.3.33
- 8.2.31 to 8.2.33

MariaDB from:
- 11.8.6 to 11.8.8
- 11.4.10 to 11.4.12
- 10.11.16 to 10.11.18

MySQL from:
- 9.7.0 to 9.7.2
- 8.4.9 to 8.4.11

diff --git a/php/install-php-extensions b/php/install-php-extensions
--- a/php/install-php-extensions
+++ b/php/install-php-extensions
@@ -21,7 +21,7 @@ if ! which docker-php-ext-configure >/dev/null || ! which docker-php-ext-enable 
 	exit 1
 fi
 
-IPE_VERSION=2.11.1
+IPE_VERSION=2.11.12
 
 StandWithUkraine() {
 	if test -t 1 && ! grep -Eq '^VERSION=.*jessie' /etc/os-release; then
@@ -771,7 +771,11 @@ buildRequiredPackageLists() {
 							buildRequiredPackageLists_libssldev="libssl-dev"
 						fi
 					else
-						buildRequiredPackageLists_libssl="libssl$buildRequiredPackageLists_sslMajorVersion"
+						if test $DISTRO_VERSION_NUMBER -ge 13; then
+							buildRequiredPackageLists_libssl="^libssl${buildRequiredPackageLists_sslMajorVersion}(t64)?\$"
+						else
+							buildRequiredPackageLists_libssl="libssl$buildRequiredPackageLists_sslMajorVersion"
+						fi
 						buildRequiredPackageLists_libssldev="libssl-dev"
 					fi
 					;;
@@ -825,11 +829,15 @@ buildRequiredPackageLists() {
 				;;
 			ddtrace@alpine)
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libgcc"
-				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile curl-dev automake libtool"
+				if test $PHP_MAJMIN_VERSION -lt 700; then
+					buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile curl-dev automake libtool"
+				fi
 				;;
 			ddtrace@debian)
-				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent $buildRequiredPackageLists_libssl"
-				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile libcurl4-openssl-dev automake libtool"
+				if test $PHP_MAJMIN_VERSION -lt 700; then
+					buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent $buildRequiredPackageLists_libssl"
+					buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile libcurl4-openssl-dev automake libtool"
+				fi
 				;;
 			dba@alpine)
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent db"
@@ -1074,6 +1082,9 @@ buildRequiredPackageLists() {
 				if [ $DISTRO_MAJMIN_VERSION -ge 319 ]; then
 					buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent ghostscript libheif libjxl libraw librsvg"
 				fi
+				if [ $DISTRO_MAJMIN_VERSION -ge 324 ]; then
+					buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libheif-aom libheif-x265"
+				fi
 				;;
 			imagick@debian)
 				if test $DISTRO_VERSION_NUMBER -ge 13; then
@@ -1081,6 +1092,7 @@ buildRequiredPackageLists() {
 				else
 					buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent ^libmagickwand-6.q16-[0-9]+$ ^libmagickcore-6.q16-[0-9]+-extra$"
 				fi
+				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent ghostscript"
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile libmagickwand-dev"
 				;;
 			imap@alpine)
@@ -1462,7 +1474,7 @@ buildRequiredPackageLists() {
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libstdc++"
 				;;
 			saxon@debian)
-				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_volatile unzip"
+				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile unzip"
 				;;
 			seasclick@alpine)
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libstdc++"
@@ -1722,6 +1734,14 @@ buildRequiredPackageLists() {
 			uv@debian)
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libuv1"
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile libuv1-dev"
+				;;
+			v8js@alpine)
+				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent libstdc++ nodejs-libs"
+				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile nodejs-dev"
+				;;
+			v8js@debian)
+				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent ^libnode[0-9]+$"
+				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile libnode-dev"
 				;;
 			vips@alpine)
 				buildRequiredPackageLists_persistent="$buildRequiredPackageLists_persistent vips"
@@ -2979,6 +2999,39 @@ You may need to:
 EOT
 }
 
+# Install the Datadog PHP tracer
+#
+# Arguments:
+#   $1: the version to be installed (optional)
+installDDTrace() {
+	printf '# Installing ddtrace\n'
+	installDDTrace_version="${1:-}"
+	if test -z "$installDDTrace_version"; then
+		installDDTrace_url='https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php'
+	else
+		installDDTrace_url="https://github.com/DataDog/dd-trace-php/releases/download/$installDDTrace_version/datadog-setup.php"
+	fi
+	installDDTrace_setup="$(mktemp -p /tmp/src)"
+	printf 'Downloading datadog-setup.php from %s\n' "$installDDTrace_url"
+	if ! curl $IPE_CURL_FLAGS -sSLf -o "$installDDTrace_setup" "$installDDTrace_url"; then
+		printf 'Failed to download %s\n' "$installDDTrace_url" >&2
+		exit 1
+	fi
+	installDDTrace_args='--php-bin=php'
+	case "${IPE_DD_APPSEC:-}" in
+		1 | y* | Y*)
+			installDDTrace_args="$installDDTrace_args --enable-appsec"
+			;;
+	esac
+	case "${IPE_DD_PROFILING:-}" in
+		1 | y* | Y*)
+			installDDTrace_args="$installDDTrace_args --enable-profiling"
+			;;
+	esac
+	php "$installDDTrace_setup" $installDDTrace_args
+	rm -f "$installDDTrace_setup"
+}
+
 # Compile the libraries specified in the COMPILE_LIBS variable
 compileLibs() {
 	if stringInList libaom "$COMPILE_LIBS"; then
@@ -3385,9 +3438,14 @@ installRemoteModule() {
 					;;
 			esac
 			installRemoteModule_tmp2=$(php -r 'echo PHP_MAJOR_VERSION . PHP_MINOR_VERSION . (ZEND_THREAD_SAFE ? "-zts" : "");')
+			if test -z "$installRemoteModule_version"; then
+				installRemoteModule_url="https://blackfire.io/api/v1/releases/probe/php/$installRemoteModule_distro/$installRemoteModule_tmp1/$installRemoteModule_tmp2"
+			else
+				installRemoteModule_url="https://packages.blackfire.io/binaries/blackfire-php/$installRemoteModule_version/blackfire-php-${installRemoteModule_distro}_${installRemoteModule_tmp1}-php-${installRemoteModule_tmp2}.tar.gz"
+			fi
 			installRemoteModule_tmp="$(mktemp -p /tmp/src -d)"
 			cd "$installRemoteModule_tmp"
-			curl $IPE_CURL_FLAGS -sSLf --user-agent Docker https://blackfire.io/api/v1/releases/probe/php/$installRemoteModule_distro/$installRemoteModule_tmp1/$installRemoteModule_tmp2 | tar xz
+			curl $IPE_CURL_FLAGS -sSLf --user-agent Docker "$installRemoteModule_url" | tar xz
 			mv blackfire-*.so $(getPHPExtensionsDir)/blackfire.so
 			cd - >/dev/null
 			installRemoteModule_manuallyInstalled=1
@@ -3452,25 +3510,24 @@ installRemoteModule() {
 			fi
 			;;
 		ddtrace)
-			if test -z "$installRemoteModule_version"; then
-				if test $PHP_MAJMIN_VERSION -lt 700; then
-					installRemoteModule_version=0.75.0
-				fi
-				if test -z "$installRemoteModule_version"; then
-					case "$DISTRO" in
-						alpine)
-							if test $DISTRO_MAJMIN_VERSION -le 312; then
-								# cc is not supported due to a memcmp related bug
-								installRemoteModule_version=1.1.0
-							fi
-							;;
-					esac
-				fi
-			else
+			if test -n "$installRemoteModule_version"; then
 				installRemoteModule_version="$(resolvePeclStabilityVersion "$installRemoteModule_module" "$installRemoteModule_version")"
 			fi
-			if test -z "$installRemoteModule_version" || test $(compareVersions "$installRemoteModule_version" 0.75.0) -ge 0; then
+			if test $PHP_MAJMIN_VERSION -lt 700; then
+				if test -n "$installRemoteModule_version" && test $(compareVersions "$installRemoteModule_version" 1.0.0) -ge 0; then
+					printf '### ERROR ### ddtrace %s requires PHP 7.0 or later (PHP %s is in use).\n' "$installRemoteModule_version" "$PHP_MAJDOTMIN_VERSION" >&2
+					exit 1
+				fi
+				if test -z "$installRemoteModule_version"; then
+					# newer 0.x releases reject PHP 5 in their configure script
+					installRemoteModule_version=0.75.0
+				fi
 				installCargo
+			elif test -n "$installRemoteModule_version" && test $(compareVersions "$installRemoteModule_version" 1.0.0) -lt 0; then
+				installCargo
+			else
+				installDDTrace "$installRemoteModule_version"
+				installRemoteModule_manuallyInstalled=2
 			fi
 			;;
 		decimal)
@@ -3670,6 +3727,9 @@ installRemoteModule() {
 							;;
 						alpine@3.7 | alpine@3.8 | debian@9) # With newer version: "This package requires GCC 7 or higher"
 							installRemoteModule_version=1.52.1
+							;;
+						alpine@3.11 | alpine@3.12) # With 1.81.0: "/src/core/lib/promise/detail/promise_like.h:219:65: internal compiler error: in assign_temp, at function.c:982"
+							installRemoteModule_version=1.80.0
 							;;
 						alpine@3.13) # With 1.71.0, 1.72.0: "src/core/call/call_filters.h:1002:69: internal compiler error: in assign_temp, at function.c:984"
 							installRemoteModule_version=1.70.0
@@ -4334,59 +4394,85 @@ installRemoteModule() {
 					installRemoteModule_edition=EE
 					;;
 			esac
+			installRemoteModule_url=
 			if test -z "$installRemoteModule_version"; then
 				if test $PHP_MAJMIN_VERSION -lt 800; then
 					installRemoteModule_version='12.3'
+				else
+					case $(uname -m) in
+						aarch64 | arm64 | armv8)
+							installRemoteModule_regexArchitecture='(linux-arm64|linux-aarch64)'
+							;;
+						*)
+							installRemoteModule_regexArchitecture=linux-x86_64
+							;;
+					esac
+					installRemoteModule_regex="https://downloads.saxonica.com/SaxonC/${installRemoteModule_edition}/[0-9]+/SaxonC${installRemoteModule_edition}-$installRemoteModule_regexArchitecture-[0-9]+-[0-9]+-[0-9]+\.zip"
+					installRemoteModule_url="$(curl $IPE_CURL_FLAGS -sSLf https://www.saxonica.com/download/c.xml | grep -Eo "$installRemoteModule_regex" | head -n 1)"
+					if test $? -ne 0 || test -z "$installRemoteModule_url"; then
+						printf "Failed to determine SaxonC download URL - Nothing matches\n%s\n" "$installRemoteModule_regex"
+						exit 1
+					fi
+					installRemoteModule_version=$(printf '%s\n' "$installRemoteModule_url" | sed 's|.*-\([0-9][0-9]*-[0-9][0-9]*-[0-9][0-9]*\)\.zip$|\1|' | tr '-' '.')
 				fi
 			fi
-			case $(uname -m) in
-				aarch64 | arm64 | armv8)
-					if test -z "$installRemoteModule_version" || test $(compareVersions "$installRemoteModule_version" '12.9') -ge 0 || test $(compareVersions "$installRemoteModule_version" '12.6') -lt 0; then
-						installRemoteModule_architecture=linux-arm64
-					else
-						installRemoteModule_architecture=linux-aarch64
-					fi
-					;;
-				*)
-					installRemoteModule_architecture=linux-x86_64
-					;;
-			esac
-			installRemoteModule_majorVersion=
-			if test -n "$installRemoteModule_version"; then
+			if test -z "$installRemoteModule_url"; then
 				installRemoteModule_majorVersion="${installRemoteModule_version%%.*}"
-				if test "$installRemoteModule_majorVersion" -ge 12; then
+				case $(uname -m) in
+					aarch64 | arm64 | armv8)
+						if test $(compareVersions "$installRemoteModule_version" '12.9') -ge 0 || test $(compareVersions "$installRemoteModule_version" '12.6') -lt 0; then
+							installRemoteModule_architecture=linux-arm64
+						else
+							installRemoteModule_architecture=linux-aarch64
+						fi
+						;;
+					*)
+						installRemoteModule_architecture=linux-x86_64
+						;;
+				esac
+				if test $(compareVersions "$installRemoteModule_version" 12.6) -ge 0; then
+					installRemoteModule_url=https://downloads.saxonica.com/SaxonC/${installRemoteModule_edition}/${installRemoteModule_majorVersion}/SaxonC${installRemoteModule_edition}-${installRemoteModule_architecture}-$(printf '%s' "$installRemoteModule_version" | tr '.' '-').zip
+				elif test $(compareVersions "$installRemoteModule_version" 12.0) -ge 0; then
 					installRemoteModule_url=https://downloads.saxonica.com/SaxonC/${installRemoteModule_edition}/${installRemoteModule_majorVersion}/libsaxon-${installRemoteModule_edition}C-${installRemoteModule_architecture}-v${installRemoteModule_version}.zip
 				else
 					installRemoteModule_url=https://downloads.saxonica.com/SaxonC/${installRemoteModule_edition}/${installRemoteModule_majorVersion}/libsaxon-${installRemoteModule_edition}C-setup64-v${installRemoteModule_version}.zip
 				fi
-			else
-				installRemoteModule_regex="https://downloads.saxonica.com/SaxonC/${installRemoteModule_edition}/[0-9]+/SaxonC${installRemoteModule_edition}-${installRemoteModule_architecture}-[0-9\-]+.zip"
-				installRemoteModule_url="$(curl $IPE_CURL_FLAGS -sSLf https://www.saxonica.com/download/c.xml | grep -Eo "$installRemoteModule_regex" | head -n 1)"
-				if test $? -ne 0 || test -z "$installRemoteModule_url"; then
-					printf "Failed to determine SaxonC download URL - Nothing matches\n%s\n" "$installRemoteModule_regex"
-					exit 1
-				fi
 			fi
-			printf 'Downloading SaxonC %s from %s\n' "$installRemoteModule_edition" "$installRemoteModule_url"
+			printf 'Downloading SaxonC %s v%s from %s\n' "$installRemoteModule_edition" "$installRemoteModule_version" "$installRemoteModule_url"
 			installRemoteModule_dir="$(getPackageSource $installRemoteModule_url)"
 			if ! test -f /usr/lib/libsaxon-*.so; then
+				echo 'Installing SaxonC shared libraries...'
 				installRemoteModule_files="$(find "$installRemoteModule_dir" \( -type f -o -type l \) \( -name 'libsaxonc-*.so*' -o -name 'libsaxon-*.so*' \))"
 				for installRemoteModule_file in $installRemoteModule_files; do
 					cp -P "$installRemoteModule_file" /usr/lib/
 				done
 				ldconfig || true
 			fi
-			installRemoteModule_files="$(find "$installRemoteModule_dir" -type f -name php8_XsltExecutable.cpp)"
-			for installRemoteModule_file in $installRemoteModule_files; do
-				sed -i 's/Z_TYPE_P(val) != NULL/Z_TYPE_P(val) != IS_NULL/g' "$installRemoteModule_file"
-			done
+			if test $(compareVersions "$installRemoteModule_version" 13.0.0) -lt 0; then
+				installRemoteModule_files="$(find "$installRemoteModule_dir" -type f -name php8_XsltExecutable.cpp)"
+				for installRemoteModule_file in $installRemoteModule_files; do
+					printf 'Applying SaxonC patch for Z_TYPE_P to %s...\n' "$installRemoteModule_file"
+					sed -i 's/Z_TYPE_P(val) != NULL/Z_TYPE_P(val) != IS_NULL/g' "$installRemoteModule_file"
+				done
+			fi
 			if test -d "$installRemoteModule_dir/php/src"; then
 				cd "$installRemoteModule_dir/php/src"
 			else
 				cd "$installRemoteModule_dir/Saxon.C.API"
 			fi
+			if test $(compareVersions "$installRemoteModule_version" 13.0.0) -eq 0; then
+				# See https://saxonica.plan.io/issues/7113
+				echo 'Applying SaxonC patch for extension source path...'
+				sed -i 's|../../../src/php8_saxon.cpp|php8_saxon.cpp|g' config.m4
+				echo 'Applying SaxonC patch for extension installation path...'
+				sed -Ei 's/^ *EXTENSION_DIR=.*//g' config.m4
+			fi
 			phpize
-			./configure --with-saxon="$installRemoteModule_dir/SaxonC${installRemoteModule_edition}"
+			if test $(compareVersions "$installRemoteModule_version" 13.0.0) -ge 0; then
+				./configure --with-saxonc="$installRemoteModule_dir/SaxonC${installRemoteModule_edition}" --with-saxonc-core="$installRemoteModule_dir/SaxonCCore${installRemoteModule_edition}"
+			else
+				./configure --with-saxon="$installRemoteModule_dir/SaxonC${installRemoteModule_edition}"
+			fi
 			make -j$(getProcessorCount) install
 			cd - >/dev/null
 			installRemoteModule_manuallyInstalled=1
@@ -5066,6 +5152,20 @@ installRemoteModule() {
 				fi
 			fi
 			;;
+		v8js)
+			if test -z "$installRemoteModule_version"; then
+				# php8 branch HEAD: there are no v8js releases on PECL/Git that support PHP 8.x
+				installRemoteModule_version=8a39efa3cf3b275e402ddf3c4f6b611a5f69a499
+			fi
+			installRemoteModule_src="$(getPackageSource "https://codeload.github.com/phpv8/v8js/tar.gz/$installRemoteModule_version")"
+			cd -- "$installRemoteModule_src"
+			phpize
+			./configure
+			make -j$(getProcessorCount)
+			make install
+			cd - >/dev/null
+			installRemoteModule_manuallyInstalled=1
+			;;
 		vld)
 			if test -z "$installRemoteModule_version"; then
 				if test $PHP_MAJMIN_VERSION -lt 700; then
@@ -5089,6 +5189,8 @@ installRemoteModule() {
 			if test -z "$installRemoteModule_version"; then
 				if test $PHP_MAJMIN_VERSION -le 702; then
 					installRemoteModule_version=1.13.0
+				elif test $PHP_MAJMIN_VERSION -le 801; then
+					installRemoteModule_version=1.14.1
 				else
 					installRemoteModule_version="$(git -c versionsort.suffix=- ls-remote --tags --refs --quiet --exit-code --sort=version:refname https://github.com/wikimedia/mediawiki-php-wikidiff2.git 'refs/tags/*.*.*' | tail -1 | cut -d/ -f3)"
 				fi
@@ -5152,6 +5254,14 @@ installRemoteModule() {
 			;;
 		xlswriter)
 			installRemoteModule_version="$(resolvePeclStabilityVersion "$installRemoteModule_module" "$installRemoteModule_version")"
+			if test -z "$installRemoteModule_version"; then
+				case "$DISTRO_VERSION" in
+					debian@8)
+						# The gcc version of Debian Jessie is too old => error: 'for' loop initial declarations are only allowed in C99 or C11 mode
+						installRemoteModule_version=1.5.8
+						;;
+				esac
+			fi
 			if test -z "$installRemoteModule_version" || test $(compareVersions "$installRemoteModule_version" 1.2.7) -ge 0; then
 				# enable reader supports?
 				addConfigureOption enable-reader yes
@@ -5660,12 +5770,16 @@ mkdir -p /tmp/pickle.tmp
 IPE_ERRFLAG_FILE="$(mktemp -p /tmp/src)"
 CONFIGURE_FILE=/tmp/configure-options
 IPE_APK_FLAGS=''
+IPE_CURL_FLAGS='--retry 3 --retry-delay 5 --connect-timeout 15'
+if curl --help | grep -q -- '--retry-all-errors'; then
+	IPE_CURL_FLAGS="$IPE_CURL_FLAGS --retry-all-errors"
+fi
+if curl --help | grep -q -- '--retry-connrefused'; then
+	IPE_CURL_FLAGS="$IPE_CURL_FLAGS --retry-connrefused"
+fi
 case "${IPE_INSECURE:-}" in
 	1 | y* | Y*)
-		IPE_CURL_FLAGS='-k'
-		;;
-	*)
-		IPE_CURL_FLAGS=''
+		IPE_CURL_FLAGS="$IPE_CURL_FLAGS -k"
 		;;
 esac
 setDistro
